helmDefaults:
  createNamespace: false

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: nginx
    namespace: poc-helmfile
    chart: bitnami/nginx
    values:
      - nginx-values.yaml

  - name: postgresql
    namespace: poc-helmfile
    chart: bitnami/postgresql
    values:
      - postgresql-values.yaml