## create the sa account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-sa-demo
  namespace: democonsole
--- 
## give right on the namespace for this SA
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-sa-demo-rolebinding
  namespace: democonsole
subjects:
  - kind: ServiceAccount
    name: my-sa-demo
    namespace: democonsole
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: my-sa-demo-token
  namespace: democonsole
  annotations:
    kubernetes.io/service-account.name: my-sa-demo
type: kubernetes.io/service-account-token
