apiVersion: v1
kind: Secret
metadata:
  name: nativeng-superuser
  namespace: demonativepg
type: kubernetes.io/basic-auth
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: nativeng-user
  namespace: demonativepg
type: kubernetes.io/basic-auth
data:
  password: Ym9uYW56YQ==
  username: Ym9uYW56YQ==