apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-password-secret
  namespace: democrunchy
type: Opaque
data:
  hippo-password: SmtTbGRza0FBMjE=
---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGAdmin
metadata:
  name: crunchypgadm
  namespace: democrunchy
spec:
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  serverGroups:
    - name: all
      # An empty selector selects all postgresclusters in the Namespace
      postgresClusterSelector: {}
  users:
  - username: hippo@example.com
    role: Administrator
    passwordRef:
      name: pgadmin-password-secret
      key: hippo-password
---
apiVersion: v1
kind: Service
metadata:
  namespace: democrunchy
  name: pgadmincrunchy
  labels:
    app: pgadmincrunchy
spec:
  type: ClusterIP
  selector:
    postgres-operator.crunchydata.com/role: pgadmin
  ports:
    - name: serviceport
      port: 5050
      targetPort: 5050