apiVersion: v1
kind: Secret
metadata:
  name: nativeng-superuser
  namespace: demonativepg
type: kubernetes.io/basic-auth
data:
  username: xxxxxxxx= #base64 encoded
  password: xxxxxxxx= #base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: nativeng-user
  namespace: demonativepg
type: kubernetes.io/basic-auth
data:
  password: xxxxxxxx= #base64 encoded
  username: xxxxxxxx= #base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-nativeng-demo8
  namespace: demonativepg
type: Opaque
data:
  DBUSER: xxxxxxxx= #base64 encoded
  DBPASS: xxxxxxxx= #base64 encoded
