kind: Service
apiVersion: v1
metadata:
  name: windows-service-iis
  namespace: demokubevirt
spec:
  selector:
    vm.kubevirt.io/name: windows-iis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
--- 
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: windows-route-iis
  namespace: demokubevirt
  labels:
    ct-router-type: public
spec:
  host: iis-windows.apps-ocp01-{your-id}.paas.cloud-temple.com # to edit
  to:
    kind: Service
    name: windows-service-iis
    weight: 100
  port:
    targetPort: 80
  tls:
    termination: edge